name: Deploy Food Ordering System

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn clean install -DskipTests
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Create EKS cluster
      run: |
        eksctl get cluster --name food-ordering-cluster || \
        eksctl create cluster \
          --name food-ordering-cluster \
          --region us-east-1 \
          --nodegroup-name standard-workers \
          --node-type t3.medium \
          --nodes 3
          
    - name: Setup kubectl for EKS
      run: aws eks update-kubeconfig --name food-ordering-cluster --region us-east-1
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Create ECR repositories
      run: |
        for service in order-service payment-service restaurant-service customer-service frontend-service; do
          aws ecr describe-repositories --repository-names $service || aws ecr create-repository --repository-name $service
        done
      
    - name: Build and push Docker images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Only build Docker images for the container modules
        echo "Building order-service Docker image..."
        cd order-service/order-container
        mvn spring-boot:build-image -DskipTests
        docker tag com.food.ordering.system/order.service:1.0-SNAPSHOT $ECR_REGISTRY/order-service:latest
        docker push $ECR_REGISTRY/order-service:latest
        cd ../..
        
        echo "Building payment-service Docker image..."
        cd payment-service/payment-container
        mvn spring-boot:build-image -DskipTests
        docker tag com.food.ordering.system/payment.service:1.0-SNAPSHOT $ECR_REGISTRY/payment-service:latest
        docker push $ECR_REGISTRY/payment-service:latest
        cd ../..
        
        echo "Building restaurant-service Docker image..."
        cd restaurant-service/restaurant-container
        mvn spring-boot:build-image -DskipTests
        docker tag com.food.ordering.system/restaurant.service:1.0-SNAPSHOT $ECR_REGISTRY/restaurant-service:latest
        docker push $ECR_REGISTRY/restaurant-service:latest
        cd ../..
        
        echo "Building customer-service Docker image..."
        cd customer-service/customer-container
        mvn spring-boot:build-image -DskipTests
        docker tag com.food.ordering.system/customer.service:1.0-SNAPSHOT $ECR_REGISTRY/customer-service:latest
        docker push $ECR_REGISTRY/customer-service:latest
        cd ../..
        
        echo "Building frontend Docker image..."
        cd frontend-service
        docker build -t frontend-service:latest .
        docker tag frontend-service:latest $ECR_REGISTRY/frontend-service:latest
        docker push $ECR_REGISTRY/frontend-service:latest
        cd ..
        
    - name: Create modified deployment file
      run: |
        cp ./infrastructure/k8s/application-deployment-local.yml ./application-deployment-cloud.yml
        
        # Update image references in deployment file
        ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
        sed -i "s|image: com.food.ordering.system/order.service:1.0-SNAPSHOT|image: $ECR_REGISTRY/order-service:latest|g" ./application-deployment-cloud.yml
        sed -i "s|image: com.food.ordering.system/payment.service:1.0-SNAPSHOT|image: $ECR_REGISTRY/payment-service:latest|g" ./application-deployment-cloud.yml
        sed -i "s|image: com.food.ordering.system/restaurant.service:1.0-SNAPSHOT|image: $ECR_REGISTRY/restaurant-service:latest|g" ./application-deployment-cloud.yml
        sed -i "s|image: com.food.ordering.system/customer.service:1.0-SNAPSHOT|image: $ECR_REGISTRY/customer-service:latest|g" ./application-deployment-cloud.yml
        
        # Fix Kafka bootstrap server URL (remove http:// prefix if present)
        sed -i 's|value: "http://my-release-kafka:9092"|value: "my-release-kafka:9092"|g' ./application-deployment-cloud.yml
        
    - name: Create frontend deployment file
      run: |
        cat <<EOF > ./infrastructure/k8s/frontend-deployment.yml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: frontend-deployment
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: frontend
          template:
            metadata:
              labels:
                app: frontend
            spec:
              containers:
              - name: frontend
                image: ${{ steps.login-ecr.outputs.registry }}/frontend-service:latest
                ports:
                - containerPort: 80
                env:
                - name: REACT_APP_CUSTOMER_API_URL
                  value: "http://customer-service:8184"
                - name: REACT_APP_ORDER_API_URL
                  value: "http://order-service:8181"
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: frontend-service
        spec:
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: 80
          selector:
            app: frontend
        EOF
        
    - name: Setup Helm
      uses: azure/setup-helm@v3
      
    - name: Clean up previous Kafka installations
      run: |
        helm uninstall my-release 2>/dev/null || true
        helm uninstall schema 2>/dev/null || true
        kubectl delete pvc --all 2>/dev/null || true
        
    - name: Install Kafka with proper settings
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm install my-release bitnami/kafka \
          --version 18.5.0 \
          --set persistence.enabled=false \
          --set zookeeper.persistence.enabled=false \
          --set replicaCount=1 \
          --set resources.requests.memory=512Mi \
          --set resources.requests.cpu=250m \
          --set zookeeper.resources.requests.memory=256Mi \
          --set zookeeper.resources.requests.cpu=100m \
          --set zookeeper.enabled=true
        
    - name: Wait for Kafka to be ready
      run: |
        echo "Waiting for Kafka to be ready..."
        # Add some initial delay to give pods time to start
        sleep 60
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=kafka,app.kubernetes.io/instance=my-release --timeout=300s || true
        
        # Verify Kafka is accessible
        echo "Verifying Kafka connectivity..."
        kubectl run test-kafka-conn --image=bitnami/kafka:latest --rm -it --restart=Never -- \
          kafka-topics.sh --bootstrap-server my-release-kafka:9092 --list || true
        
    - name: Install Schema Registry with correct Kafka address
      run: |
        # Create a ConfigMap with a custom configuration for Schema Registry
        cat <<EOF > schema-registry-config.yaml
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: schema-registry-config
        data:
          schema-registry.properties: |
            kafkastore.bootstrap.servers=PLAINTEXT://my-release-kafka:9092
            schema.registry.bootstrap.servers=PLAINTEXT://my-release-kafka:9092
        EOF
        kubectl apply -f schema-registry-config.yaml
        
        # Install Schema Registry with the correct configuration
        helm install schema bitnami/schema-registry \
          --set kafka.enabled=false \
          --set externalKafka.brokers=my-release-kafka:9092 \
          --set configurationOverrides."kafkastore\.bootstrap\.servers"=PLAINTEXT://my-release-kafka:9092 \
          --set configurationOverrides."schema\.registry\.bootstrap\.servers"=PLAINTEXT://my-release-kafka:9092 \
          --set configurationOverrides."listener"=http://0.0.0.0:8081 \
          --set extraEnvVars[0].name=SCHEMA_REGISTRY_KAFKA_BROKERS \
          --set extraEnvVars[0].value=PLAINTEXT://my-release-kafka:9092
          
    - name: Deploy Postgres
      run: kubectl apply -f ./infrastructure/k8s/postgres-deployment.yml
      
    - name: Wait for Schema Registry to be ready
      run: |
        echo "Waiting for Schema Registry to be ready..."
        sleep 60
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=schema-registry,app.kubernetes.io/instance=schema --timeout=300s || true
        
        # Check Schema Registry status and logs
        echo "Schema Registry status:"
        kubectl get pods | grep schema
        echo "Schema Registry logs:"
        kubectl logs $(kubectl get pods | grep schema | awk '{print $1}') || true
        
    - name: Create Kafka topics
      run: |
        cat <<EOF > kafka-topics-job.yml
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: kafka-topics-setup
        spec:
          ttlSecondsAfterFinished: 100
          template:
            spec:
              containers:
              - name: kafka-client
                image: bitnami/kafka:latest
                command:
                - "/bin/bash"
                - "-c"
                - |
                  sleep 30  # Wait for Kafka to be fully ready
                  kafka-topics.sh --bootstrap-server my-release-kafka:9092 --create --if-not-exists --topic payment-request --replication-factor 1 --partitions 3
                  kafka-topics.sh --bootstrap-server my-release-kafka:9092 --create --if-not-exists --topic payment-response --replication-factor 1 --partitions 3
                  kafka-topics.sh --bootstrap-server my-release-kafka:9092 --create --if-not-exists --topic restaurant-approval-request --replication-factor 1 --partitions 3
                  kafka-topics.sh --bootstrap-server my-release-kafka:9092 --create --if-not-exists --topic restaurant-approval-response --replication-factor 1 --partitions 3
                  kafka-topics.sh --bootstrap-server my-release-kafka:9092 --create --if-not-exists --topic customer --replication-factor 1 --partitions 3
              restartPolicy: Never
          backoffLimit: 4
        EOF
        kubectl apply -f kafka-topics-job.yml
        
    - name: Wait for Kafka topic creation
      run: |
        echo "Waiting for Kafka topics to be created..."
        sleep 30
        kubectl wait --for=condition=complete job/kafka-topics-setup --timeout=300s || true
        
    - name: Configure Schema Registry for Microservices
      run: |
        # Make sure the Schema Registry URL is correct
        SCHEMA_REGISTRY_URL=http://schema-schema-registry:8081
        
        # Configure services to use Schema Registry
        kubectl set env deployment/customer-deployment \
          SPRING_KAFKA_PROPERTIES_VALUE_SERIALIZER=io.confluent.kafka.serializers.KafkaAvroSerializer \
          SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY_URL
        
        kubectl set env deployment/order-deployment \
          SPRING_KAFKA_PROPERTIES_VALUE_SERIALIZER=io.confluent.kafka.serializers.KafkaAvroSerializer \
          SPRING_KAFKA_PROPERTIES_VALUE_DESERIALIZER=io.confluent.kafka.serializers.KafkaAvroDeserializer \
          SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY_URL \
          SPRING_KAFKA_PROPERTIES_SPECIFIC_AVRO_READER=true
        
        kubectl set env deployment/payment-deployment \
          SPRING_KAFKA_PROPERTIES_VALUE_SERIALIZER=io.confluent.kafka.serializers.KafkaAvroSerializer \
          SPRING_KAFKA_PROPERTIES_VALUE_DESERIALIZER=io.confluent.kafka.serializers.KafkaAvroDeserializer \
          SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY_URL \
          SPRING_KAFKA_PROPERTIES_SPECIFIC_AVRO_READER=true
        
        kubectl set env deployment/restaurant-deployment \
          SPRING_KAFKA_PROPERTIES_VALUE_SERIALIZER=io.confluent.kafka.serializers.KafkaAvroSerializer \
          SPRING_KAFKA_PROPERTIES_VALUE_DESERIALIZER=io.confluent.kafka.serializers.KafkaAvroDeserializer \
          SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY_URL \
          SPRING_KAFKA_PROPERTIES_SPECIFIC_AVRO_READER=true
        
    - name: Deploy microservices
      run: kubectl apply -f ./application-deployment-cloud.yml
        
    - name: Deploy frontend
      run: kubectl apply -f ./infrastructure/k8s/frontend-deployment.yml
        
    - name: Get service endpoints
      run: |
        echo "Service endpoints:"
        kubectl get svc
        
    - name: Restart deployments to apply changes
      run: |
        kubectl rollout restart deployment customer-deployment order-deployment payment-deployment restaurant-deployment frontend-deployment
        
    - name: Wait for services to be ready
      run: |
        echo "Waiting for all services to be ready..."
        kubectl wait --for=condition=available deployment/customer-deployment --timeout=300s || true
        kubectl wait --for=condition=available deployment/order-deployment --timeout=300s || true
        kubectl wait --for=condition=available deployment/payment-deployment --timeout=300s || true
        kubectl wait --for=condition=available deployment/restaurant-deployment --timeout=300s || true
        kubectl wait --for=condition=available deployment/frontend-deployment --timeout=300s || true
        
        echo "Testing the services..."
        
        # Get the service endpoints
        CUSTOMER_ENDPOINT=$(kubectl get svc customer-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        ORDER_ENDPOINT=$(kubectl get svc order-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        FRONTEND_ENDPOINT=$(kubectl get svc frontend-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        
        echo "Customer service: http://$CUSTOMER_ENDPOINT:8184"
        echo "Order service: http://$ORDER_ENDPOINT:8181"
        echo "Frontend service: http://$FRONTEND_ENDPOINT"
        
        echo "Deployment complete"
